"""Added food FoodCategory

Revision ID: 45861c478016
Revises: 63c2507537dc
Create Date: 2023-10-15 23:24:30.007935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45861c478016'
down_revision: Union[str, None] = '63c2507537dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_food_categories_category_id'), 'food_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_food_categories_category_name'), 'food_categories', ['category_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_categories_category_name'), table_name='food_categories')
    op.drop_index(op.f('ix_food_categories_category_id'), table_name='food_categories')
    op.drop_table('food_categories')
    # ### end Alembic commands ###
