"""Added FoodItem

Revision ID: 27d1e0071218
Revises: 45861c478016
Create Date: 2023-10-15 23:25:46.659951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d1e0071218'
down_revision: Union[str, None] = '45861c478016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.category_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_food_items_item_id'), 'food_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_food_items_item_name'), 'food_items', ['item_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_item_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_item_id'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
