"""Added more colums to order

Revision ID: 02cef8864c74
Revises: 2ff7513903cc
Create Date: 2024-01-15 16:05:22.465542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02cef8864c74'
down_revision: Union[str, None] = '2ff7513903cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_charge', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('extra_charge_reason', sa.Text(), nullable=True))
    op.add_column('order', sa.Column('extra_charge', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('order_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_type')
    op.drop_column('order', 'extra_charge')
    op.drop_column('order', 'extra_charge_reason')
    op.drop_column('order', 'delivery_charge')
    # ### end Alembic commands ###
